graphic_reset(40, ...
    'DefaultAxesMinorGridAlpha', 0.05, ...
    'DefaultAxesMinorGridLineStyle', '-', ...
    'DefaultTextInterpreter', 'latex', ...
    'DefaultLegendInterpreter', 'latex', ...
    'DefaultAxesLineWidth', 3, ...
    'DefaultLineLineWidth', 4, ...
    'DefaultAxesLabelFontSize', 1.5, ...
    'DefaultAxesTitleFontSize', 1.5);

figure; hold on; 
g_vec = [0.1,0.25,0.5,1,2,4,10]; 
cmap = return_colorbrewer('Spectral', length(g_vec))*0.9;
x = -5:0.01:5; 
lgnd_objs = arrayfun(@(g,i) plot(x, tanh(g*x), 'color', cmap(i,:), ...
    'displayname', sprintf('g = %g', g)), g_vec, 1:length(g_vec));  
yline(0, ':k', 'linewidth',3);
xline(0, ':k', 'linewidth',3);
xlabel('$x$'); ylabel('$\tanh(gx)$');
legend(lgnd_objs)
despline


export_fig('figures/Fig1', '-r200', '-p0.02');