addpath(genpath('.')); 
addpath(genpath(get_remembered_places('genfun')))
addpath(genpath(get_remembered_places('extpkg')))
rmpath('./scratch');

graphic_reset(25, ...
    'DefaultAxesMinorGridAlpha', 0.05, ...
    'DefaultAxesMinorGridLineStyle', '-', ...
    'DefaultTextInterpreter', 'latex', ...
    'DefaultLegendInterpreter', 'latex', ...
    'DefaultAxesLineWidth', 2, ...
    'DefaultLineLineWidth', 3, ...
    'DefaultAxesLabelFontSize', 1.25, ...
    'DefaultAxesTitleFontSize', 1.25);