addpath(genpath('.')); 
addpath(genpath('../dependencies'));

graphic_reset(15, ...
    'DefaultAxesLineWidth', 2, ...
    'DefaultLineLineWidth', 3, ...
    'DefaultAxesLabelFontSize', 2, ...
    'DefaultAxesTitleFontSize', 1.8);